import fs from "fs";
import path from "path";

// Check potential output directories generated by TanStack Start / Nitro / Vite
const outputPublic = path.resolve(".output/public");
const vercelStatic = path.resolve(".vercel/output/static");
const distDir = path.resolve("dist");

console.log("[build-post] Verifying build artifacts...");

if (fs.existsSync(outputPublic)) {
  console.log(`[build-post] Copying ${outputPublic} -> ${distDir}`);
  fs.mkdirSync(distDir, { recursive: true });
  fs.cpSync(outputPublic, distDir, { recursive: true });
} else if (fs.existsSync(vercelStatic)) {
  console.log(`[build-post] Copying ${vercelStatic} -> ${distDir}`);
  fs.mkdirSync(distDir, { recursive: true });
  fs.cpSync(vercelStatic, distDir, { recursive: true });
} else if (fs.existsSync(distDir)) {
  console.log(`[build-post] Found ${distDir}`);
} else {
  console.warn("[build-post] Warning: No build directory (.output/public, .vercel/output/static, or dist) found.");
}
